### ISSUE TITLE
Add curl command to for server assignment

### ISSUE THREAD

**Issue by liorm0505** [hllhll/pyekonlib#1]
Since automatic configuration is still TBD, maybe the author can add single line curl command to config device to new local server

**Comment by hllhll** [comment]
It may be more complicated then that. I believe there's a quirk in the tcp stack of the device,
recommended method is by [Burp suite](https://portswigger.net/burp/communitydownload) (Super-overkill, but that works.) (Repeater tab), if anybody want he/she invited to try telnet or netcat with pre-made file with the HTTP request and pipe it, such as:
```
ncat 192.168.1.22 80 < req.txt
```

**Comment by hllhll** [comment]
Fixed in https://github.com/hllhll/pyekonlib/commit/5628f407e190ce357bc95d78e42959a2d29f7002

**Comment by hllhll** [comment]
A Specific note was placed in the readme in https://github.com/hllhll/pyekonlib/commit/eb1424a0c9242be02f5bc16399f210f8b722f510
